version: "3"

services:
  backend:
    image: node:18
    command: yarn start:dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./back_nestjs:/app/

  frontend:
    image: node:18
    command: yarn dev
    working_dir: /app
    depends_on:
      - backend
    ports:
      - "3001:3000"
    volumes:
      - ./front_nextjs:/app